#!/bin/sh

show_help(){

    printf 'Usage:
    sv-enable <service-name>

    Enabling a service will make it autostart
'
}
if [ -z "$1" ];then
    show_help
    exit 1
fi
if [ -u "$SVDIR" ];then
    >&2 echo "Error: SVDIR not set"
    exit 1
fi
rm -f "$SVDIR/$1/down"
sv up $1
